### ISSUE TITLE
Generated waveform with audiowaveform is half-complete

### ISSUE THREAD

**Issue by BriceN** [katspaugh/wavesurfer.js#1181]
The command I use :
`audiowaveform -i myfile.mp3 -b 16 -o myfile.json`

What i get in my application : 
![capture2](https://user-images.githubusercontent.com/8823428/28817845-beb2b1d8-76a9-11e7-86dd-d699e1a8e33a.PNG)
(missing part in yellow, the blue peaks match the music perfectly )

Snippet of my json file : 
`{"sample_rate":44100,"samples_per_pixel":4410,"bits":16,"length":2318,"data":[-8,99,-2,91,7,167,-2512,2011,-2447,2009,-2475,1922,-2338,1626,-2356,1624,-2556,1697,-3050,1899,-3175,2268,-2978,2105,-2925,.....`

What is the problem here ? Not enough peaks data are generated ?

Also i use :
` normalize: true` as wavesurfer param
And I filter the peaks data like that :
`                response.data.data.filter(function(value) {
                    return value >= 0;
                })`

**Comment by entonbiba** [comment]
this will be fixed with pr #1182

**Comment by GitHubRakeshSharma** [comment]
I had the same issue. I found that the drawLineToContext method uses the canvas size in px as top limit in the drawing loop. I just changed it to be the local length parameter which is half the length of the converted array of peaks (meaning the one where negative values have been added alternatingly).

**Comment by mspae** [comment]
Should be fixed now. Please check if it works for you now. @GitHubRakeshSharma @BriceN 

To install a npm package directly from github, do:
`npm install katspaugh/wavesurfer.js#master`

**Comment by GitHubRakeshSharma** [comment]
I did import the new version from the masterbranch... BUT: now the dist folder is missing. Can you generate one or could you tell me how to efficiently genrate one myself?

**Comment by mspae** [comment]
@GitHubRakeshSharma My bad, use this:

```
git clone git@github.com:katspaugh/wavesurfer.js.git && cd wavesurfer.js && npm i && npm run build && npm link && cd ../ && npm link wavesurfer.js
```

it …
* clones wavesurfer.js into the directory `wavesurfer.js`
* installs the dependencies in that project
* builds it (the `dist` directory)
* [links it](https://docs.npmjs.com/cli/link) so wavesurfer is resolved to that copy

to update you just `git pull` inside the `wavesurfer.js` directory.

This is just a quick-fix until the next beta release comes out.

**Comment by GitHubRakeshSharma** [comment]
I am sorry to say that now it throws this Error... seems like some policy issue:
```
Cloning into 'wavesurfer.js'...
Warning: Permanently added the RSA host key for IP address '192.30.253.113' to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by X-Raym** [comment]
@mspae 
> This is just a quick-fix until the next beta release comes out.

When can we expect the next beta ? :)
(I assume it will have others bug fixes and enhancement so maybe it worths waiting a bit more to have an official build rather than making a custom one ?)

**Comment by mspae** [comment]
@X-Raym see the discussion at #1092 – i think/hope soon.

@GitHubRakeshSharma I don't know how your github ssh is set up. you may need to adjust cloning command.

**Comment by GitHubRakeshSharma** [comment]
I fixed my SSH and did the above... now I receive the following (seems like LINT does this):
./src/render_source/wavesurfer.js/dist/wavesurfer.min.js
  Line 6:  'define' is not defined     no-undef
  Line 6:  'define' is not defined     no-undef
  Line 6:  Unexpected use of 'screen'  no-restricted-globals
  Line 6:  Unexpected use of 'screen'  no-restricted-globals

I cannot find any restrictions in the lint config... is this a known thing? Do I overlook the obvious?

**Comment by mspae** [comment]
@GitHubRakeshSharma When do you get this error? When you run `npm run build`?

**Comment by mspae** [comment]
@X-Raym  @GitHubRakeshSharma  Have you tried out the new beta 2 version?

**Comment by X-Raym** [comment]
@mspae Just tested: seems to be good for me! Both peak generation and peak display from it! Thx !

**Comment by mspae** [comment]
I'll close this. If anybody still experiences problems please comment and I'll reopen.
