### ISSUE TITLE
15-minute splitChannel mp3s crash on iOS

### ISSUE THREAD

**Issue by DrLongGhost** [katspaugh/wavesurfer.js#2116]
### Wavesurfer.js version(s):
4.2.0

### Browser and operating system version(s):
iPhone 6S on iOS 14.2 & iPad Mini 5 on iOS 13.7

### Code needed to reproduce the issue:
https://jsfiddle.net/dan24678/wspmbjvk/22/show 

^ This code pen has a button to destroy any preexisting wavesurfer and add a new one.

On an iPhone 6S, it crashes immediately on the first click. On the iPad Mini 5, it crashes the fifth time you destroy/add wavesurfer.

### Use behaviour needed to reproduce the issue:
Use a 15-minute audio file with splitChannels: true on an iOS device. Most serious/more frequent crashes occur on older, weaker phones.

### Full Details and Findings:
I strongly suspect this issue is tied to memory usage. Shorter audio files make the issue less prevalent. As does setting splitChannels to false. Newer iPhones have more memory than the iPhone 6S's 2GB RAM, resulting in fewer or no crashes.

Interestingly, the issue also manifests itself on Safari on Mac desktops/laptops as well, although in a less serious way. On Desktop Safari, excessive creation/destroy of wavesurfer instances will not crash the browser but will result in a warning banner shown across the top of the browser: "This webpage is using significant energy. Closing it may improve the responsiveness of your Mac."

Also, there definitely seems to be some overlap between this issue and the work being done on https://github.com/katspaugh/wavesurfer.js/issues/1940

While not using splitChannels, only using newer phones, using shorter files or using pre-rendered peak files are all ways to prevent crashes, these also are not real solutions to this problem. However, there are 2 partial mitigations which seem to help:
- Using the "MediaElementWebAudio" backend any time Safari is detected. This provides a huge improvement and seems to prevent almost all crashes on newer iPads and iPhones
- Calling "delete wavesurfer.backend.buffer". This **seems** to provide a small improvement. But it's also possible this is a placebo effect and actually provides no benefit.

Although the combination of these 2 fixes seems to provide acceptable performance, the reality is that it does not in a Production setting. In Production, Wavesurfer is often combined with a framework such as Vue.js or React, which eats away at the device RAM further, leaving less memory available for Wavesurfer and reintroducing crashes on the very first wavesurfer instantiation on older iPhones (6S and probably 7's). For this reason, I am opening this ticket to share my findings and see if anyone can suggest further optimizations to prevent crashes on iOS devices when Wavesurfer is used with web frameworks or used to load files larger than 15 minutes.

I have prepared 6 different JsFiddles showing 6 different configurations and testing each on my iPhone and iPad. You can see the improvements introduced by the configuration changes (ordered below from least to most stable):

**WebAudio Backend**

https://jsfiddle.net/dan24678/wspmbjvk/22/show  

iphone 6S: cannot load once / crashes on second click
Ipad: crashes on 5th click

----------------------------------------------

**MediaElement Backend**

https://jsfiddle.net/dan24678/ms67ouzq/1/show

iphone 6S: loads once then crashes after 2nd click
iPad: Does not crash after 20+ clicks

------------------------------------------------

**MediaElementWebAudio Backend**

https://jsfiddle.net/dan24678/ms67ouzq/3/show

iphone 6S: Does not crash after 20+ clicks but still rare crashes
iPad: Does not crash after 20+ clicks

------------------------------------------------

**WebAudio Backend w/ backend cleanup**

https://jsfiddle.net/dan24678/ms67ouzq/8/show

iphone 6S: crashes on 3rd click
Ipad: crashes on 5th click

----------------------------------------------

**MediaElement Backend w/ backend cleanup**

https://jsfiddle.net/dan24678/ms67ouzq/9/show

iphone 6S: Does not crash after 20+ clicks but still rare crashes
iPad: Does not crash after 20+ clicks but still rare crashes

------------------------------------------------

**MediaElementWebAudio Backend w/ backend cleanup**

https://jsfiddle.net/dan24678/ms67ouzq/11/show

iphone 6S: Does not crash after 20+ clicks but still rare crashes
iPad: Does not crash after 20+ clicks

**Comment by sundayz** [comment]
Great job with all the testing. Yes it seems to be the same issue as #1940

I wanted to mention that if you can use cached peaks in your use case, you should, because it seems to reduce memory usage a LOT. In the application I work on we can create 100+ wavesurfer instances when using MediaElementWebAudio and cached peaks.

**Comment by DrLongGhost** [comment]
@sundayz -- A few questions/comments:

- As I mentioned, while I do consider this issue serious, I view the idea of introducing peak data via a separate ajax request as far too much trouble and added complexity.
- I did consider setting "partialRender: true" as the documentation states it will "Use the PeakCache to improve rendering speed of large waveforms.".  What does this actually mean? Is it caching in the sense that it only speeds up the second time you try to load the same data? Is this likely to help with the iOS crashes I'm seeing?
- Similarly, setting "pixelRatio: 1" instead of "pixelRatio: 2" says that it will speed up rendering, which implies it might help with the crashes. But it causes the font used on the timeline plugin to look very blurry. A possible mitigation here would be to use "pixelRatio: 1" only in Safari so all other browsers have a sharper timeline display. Do you think "pixelRatio: 1" is likely to improve memory usage and reduce crashes?

I'm happy to do additional fiddles and tests on one or both of these settings, if you think they might help but I figured I'd check in first to avoid wasting my time if it seems probably that neither setting would actually reduce the overall RAM used by wavesurfer.

**Comment by sundayz** [comment]
Both partialRender and pixelRatio seem to be renderer related options (for html5 canvas) which is used to draw the waveform. I don't know how much they change about performance. 

Here is a firefox memory snapshot of a production app built with vue that uses wavesurfer + cached waveforms. (backend: MediaElement)
![image](https://user-images.githubusercontent.com/11685806/100266859-6bf16680-2f4a-11eb-9d30-e214adb5eff7.png)

And here is a memory snapshot of your jsfiddle (backend: MediaElement)
![image](https://user-images.githubusercontent.com/11685806/100266890-79a6ec00-2f4a-11eb-8879-d9c08d94ffb7.png)


300MB vs 25MB. So as you can see the problem is somewhere in the wavesurfer code that generates the waveform. That's why I recommend caching peaks yourself and providing them when you call `wavesurfer.load(audio, peaks)`

Hope that helps

**Comment by thijstriemstra** [comment]
Is the iPhone 6S still supported by Apple? Something to consider; stop trying to support it when Apple stopped updates for that version of iOS/Safari/iPhone.

**Comment by DrLongGhost** [comment]
@thijstriemstra -- I was about to switch my Production site to the "MediaElementWebAudio" backend but then I realized that this backend completely breaks playback.

In this fiddle for example (https://jsfiddle.net/dan24678/ms67ouzq/3/show) when you load Wavesurfer with the "Click Me" button then click "Play", there is no audio. This appears to happen in all browsers. But if you use either of the other 2 backends/fiddles then playback works fine.

This seems like a pretty serious bug. Is this something you can fix so that I can start using the "MediaElementWebAudio" backend when Safari is detected (to partially address the crashing issues there)? Or is this not a bug or somehow expected behavior?

If it is a bug, I'm happy to make a separate ticket for this. I figured I'd check first in here, in case it's not.

Thanks.

**Comment by sundayz** [comment]
In the console when I try your fiddle: `The HTMLMediaElement passed to createMediaElementSource has a cross-origin resource, the node will output silence`

Try this: #2014
Should fix it

**Comment by DrLongGhost** [comment]
@sundayz, @thijstriemstra  -- Thanks for the help. I did a bunch more testing but this is taking me deep down the rabbit hole. Here's what I've found:

- All browsers are susceptible to CORS problems using "MediaElementWebAudio". But when these happen in Safari, it does not show any errors in the console. This makes it hard to debug CORS issues in Safari.
- Chrome/Firefox *do* show CORS problems in the console -- "MediaElementAudioSource outputs zeroes due to CORS access restrictions" and "The HTMLMediaElement passed to createMediaElementSource has a cross-origin resource, the node will output silence" are the respective errors.
- The fix suggested in #2014 works for to remove the error and restore playback in Chrome, FF and Safari in JsFiddle.
- However, there appear to be other cases where the fix does not work. I am able to duplicate this on the site where I ultimately use Wavesurfer but cannot replicate in a simple JsFiddle. 
- When I try in a JsFiddle (such as https://jsfiddle.net/dan24678/ms67ouzq/18/show) the resulting code works everywhere
- But when I try similar code on my development version of our production site, playback is broken in all browsers except Firefox. Clicking Play makes the cursor move, but no sound can be heard. I am using the exact same S3 mp3 as the working JSFiddle with the same CORS headers set by AWS. Safari shows no errors. Chrome shows one thing that may be related: "wavesurfer.min.js?b9b7:6 The AudioContext was not allowed to start. It must be resumed (or created) after a user gesture on the page." 
- However, the aforementioned AudioContext warning also appears in Chrome if the backend is switched back to AudioContext and when I do that, playback works fine.

So... to reiterate where I'm at now... I can make a JSFiddle that loads my S3 mp3 via "MediaElementWebAudio" and it works fine. But when I try to do the same thing on my actual site, it works in Firefox but won't play in Chrome or Safari. No errors in Safari; and Chrome only has the preexisting error (false alarm?) about AudioContext user gestures.

As of right now, I'm still stuck having to use the WebAudio backend on Safari because even though it crashes more often than MediaElementWebAudio does, at least I know playback always works there.

Any ideas? A few things I can think of:
- I might try proxying the mp3 file so the fetch happens under the same domain as the page itself (which might help if the problem is actually CORS) although the lack of a clear CORS error in Chrome argues against that helping.
- Also, in case the issue is CORS-related, is there any way to make Wavesurfer use XHR instead of Fetch when using the approach recommended in #2014? Maybe that would help.
- Maybe there's something to the "AudioContext user gestures" error and I should try addressing that?

It's clearly something to do with a difference between the Fiddle and my full code, but I can't pin down exactly what the major difference is between the two.

**Comment by DrLongGhost** [comment]
Also, one funny about dropping support for iPhone 6S. The reason I know this doesn't work there is because that's the phone I own. So I'm actually pretty behind the curve but I figure if I still use one of these older phones, plenty of other people probably do. The phone is still "supported" and receiving all the latest updates from Apple, although it is admittedly the oldest model to do so.

**Comment by sundayz** [comment]
6s is a great phone :) and still supported

It sounds like you have solved the CORS problem and you are now running into the Autoplay policy problem.

Chrome has a quite restrictive "Autoplay policy", it doesn't allow sound to play unless the play() method is called after a "user interaction". From what I understand this means calling `wavesurfer.play()` inside the event handler for something like a button click.

The warning in your console is telling you to resume the audiocontext after the user has interacted with your page. Here's a code snippet that should help with that.
```js
                        // AudioContexts created on page load are suspended in Chrome
                        // You need to call resume() after user interaction (e.g. button click) to resume audio
                        if (wavesurfer.backend.ac.state === 'suspended') {
                            try {
                                await this.wavesurfer.backend.ac.resume();
                            } catch (err) {
                                console.error(err);
                            }
                        }
```

In the app that I work on, this solves the problem in Firefox, Chrome and Safari. However note that Safari is even more restrictive on autoplaying sounds and seems like it ALWAYS requires that you play() audio from a user input handler. Chrome does some kind of analysis on how much the user interacts with your page and allows autoplay based on that. 

I think this should solve your issue.

**Comment by DrLongGhost** [comment]
@sundayz -- Thanks again. That fixed Chrome but Safari is still broken. I figured out why and unfortunately, it's a deal breaker for me. Using "MediaElementWebAudio" on Safari has two serious issues:

- First, and I'm pretty impressed that I actually figured this out, but if the mp3 gets cached, it won't be playable. This was why it was failing to play on my site but still working on JSFiddle. If you view the Network tab and look at the mp3 in Safari, when you see that it downloaded it from cache instead of from the network, you'll also notice that it ends up failing to produce sound when you click Play. My guess is that reading from cache fails to internally send the necessary CORS permissions somehow and blocks Safari from full access to the file. Maybe this only happens with certain combinations of headers sent from AWS/S3 or maybe it's widespread across most files/servers. Clearing cache will allow the file to play *once* but at that point it's cached and can never be played again (until you manually clear cache).
- Even if you manage to play a file on Safari via "MediaElementWebAudio", it sounds choppy and breaks up. You can try it in [this fiddle](https://jsfiddle.net/dan24678/ms67ouzq/18/show) if you play it then click around to different spots toward the end of the file, you can eventually get it to start breaking up and stuttering, which doesn't happen with the other backends.

So, yea, I guess I'll call it at this point. "MediaElementWebAudio" in Safari is probably a dead end and we're stuck with "WebAudio" and all the crashes and memory usage that it comes with. I guess feeding in the peak data separately might be the one thing that could help, but like I said originally, that's probably more effort than I want to take on just to address a Safari-only issue.

**Comment by sundayz** [comment]
It stutters but it's not terrible on an iPhone 8. I'd say the problem lies with Safari. If we found a way to fix the decodeAudioData arraybuffer memory leak it might make things better. Until then your best bet is caching peaks

**Comment by DrLongGhost** [comment]
I just upgraded to the latest version of Mac OS ("Big Sur"). This included Safari updates and the browser on my Macbook seems much improved with Wavesurfer.

I can't do a 1-to-1 comparison anymore but I loaded a large number of multi-channel wavesurfer recordings, as well as videos via Video.js/Wavesurfer integration in our production app and did not see the memory warning. I feel like pre-update I would have seen it.

So it's possible there are memory optimizations of some sort that recently made it into Safari and might eventually find their way onto phones.

**Comment by sundayz** [comment]
@DrLongGhost Hi, apparently Safari Technology Preview includes an improved WebAudio implementation, if you get the chance you should try it out to see what effect it has.

**Comment by DrLongGhost** [comment]
@sundayz - Sure. I'll see what I can do. However, I did end up finally upgrading from an iPhone 6S to a 12 mini, so my ability to test on the lower end spectrum of iOS is now compromised. I still have the iPad Mini 5 though.

**Comment by thijstriemstra** [comment]
> I did end up finally upgrading from an iPhone 6S to a 12 mini

Ha, same here.

> so my ability to test on the lower end spectrum of iOS is now compromised.

I don't intend to support iOS lower than 14.x since it's gotten so much better.

**Comment by sundayz** [comment]
Nice! I'm pretty sure every single iOS device has the laggy audio, even the high end ones, but I haven't tried yet.

I don't think Safari Technology Preview is on iOS but "supposedly" iOS Beta 14.5 has the new WebAudio implementation, according to the webkit bug tracker.

**Comment by sundayz** [comment]
I tried on an iPhone 12 with iOS 14.4 and it stutters there too.
On a macbook pro it lags a lot less but still does. On that same macbook pro with Safari Technology Preview the lag seems to be completely gone.

**Comment by thijstriemstra** [comment]
>  "supposedly" iOS Beta 14.5 has the new WebAudio implementation, according to the webkit bug tracker.

Do you have a link for that?

**Comment by sundayz** [comment]
> 
> 
> > "supposedly" iOS Beta 14.5 has the new WebAudio implementation, according to the webkit bug tracker.
> 
> Do you have a link for that?

sure
https://bugs.webkit.org/show_bug.cgi?id=221334

**Comment by thijstriemstra** [comment]
> We've recently completely reworked (and unprefixed) our WebAudio implementation

woohoo!
