### ISSUE TITLE
Creation of unintentional, buggy regions

### ISSUE THREAD

**Issue by ManimMadhav** [katspaugh/wavesurfer.js#3642]
## Bug description:
Hi all, I have encountered a problem while working with this library which I believe might be a bug. While creating regions, there seems to be an issue with creation of regions that can be called _rogue_. I am attaching a video of how the unintended behaviour occurs. You can view the ID of the region that is being clicked on in the ```console``` on the right side.

https://github.com/katspaugh/wavesurfer.js/assets/66988314/43b5deef-376b-45a5-8f71-4ff8ef7fafb1

You can see how the regions _break_ into **two** while creating them. I have used a ```region-click``` event to check the ```region.id``` of the regions so created. When a region breaks into two, _the first half of the region does not seem to have an ID_ which makes removal of that region impossible unless I restart the program (by refreshing the webpage).

You can see how I click on ```Clear All Regions``` at the end but somehow, those _rogue_ regions do not seem to go away. Even when I click on those regions to view their ID, nothing appears in the console.
## Environment:
 - Browser: Chrome
 - Version: v7.7.9, imported from: ```import WaveSurfer from 'https://unpkg.com/wavesurfer.js@7/dist/wavesurfer.esm.js'```

## Minimal code snippet:
Regions get created by dragging:
```
wsRegions.enableDragSelection({
    color: 'rgba(0,120,0,0.3)',
});
```
Region click code:
```
wsRegions.on('region-clicked', (region) => {
    console.log(region.id);
});
```
Clearing all regions code:
```
function clearAllMaps(){
    wsRegions.clearRegions();
}
```
## Expected result:
Regions shouldn't be breaking into two for intended use.

## Obtained result:
Region created split into two.

PS: Do let me know if I can make any clarifications, it's my first time opening an issue on GitHub. Thank you!

**Comment by katspaugh** [comment]
I wasn't able to reproduce this in Chrome (mac/touchpad) in this example: https://wavesurfer.xyz/examples/?regions.js

Is there any additional code that you added that might affect it? Can you make a reproducible example on codepen?

**Comment by ManimMadhav** [comment]
hey @katspaugh. I have around 800 lines of code that I have used to create an entire application using the library. Could it be that I am trying to overwork the ```regions``` plugin? This issue is not reproducible all the time btw. Not sure why this is occuring, because I've started to face this issue only a few days ago and I have not made any changes to the code. Please let me know what I can do to further clarify the issue?

**Comment by katspaugh** [comment]
A few days ago there was a refactoring of the draggable function, so it may well be a regression. The problem is I don't know how to reproduce it.

Could you try going back to v[7.7.6](https://github.com/katspaugh/wavesurfer.js/releases/tag/7.7.6) and seeing if the bug goes away?

**Comment by ManimMadhav** [comment]
i just tried all versions of ```7.7.x```, and the bug is replicable in every version.

**Comment by katspaugh** [comment]
Is your app available on some URL?

**Comment by ManimMadhav** [comment]
noo i have not deployed it yet :/

**Comment by VaysseRobin** [comment]
I was able to reproduce the bug on [https://wavesurfer.xyz/examples/?regions.js ](https://wavesurfer.xyz/examples/?regions.js)  when I try to create several regions quickly (I've just removed the code that generates the predefined regions)

I'm on Ubuntu using Chrome with a mouse.

https://github.com/katspaugh/wavesurfer.js/assets/32324822/9dd98044-e418-4bc1-9d40-44abcb41ec41

**Comment by katspaugh** [comment]
@VaysseRobin @ManimMadhav can you reproduce it with this example? https://wavesurfer.xyz/examples/?064352f48990781f8e5328ed18f4301b (wavesurfer version prior to the draggable refactoring)

**Comment by ManimMadhav** [comment]
No @katspaugh , I can't reproduce the error here in the link you have provided.
However, I can reproduce the error in the link @VaysseRobin shared earlier.
![image](https://github.com/katspaugh/wavesurfer.js/assets/66988314/427aab2d-7d36-4c30-9d55-51f464f06d66)

**Comment by VaysseRobin** [comment]
I can't reproduce it either in this older version.

**Comment by katspaugh** [comment]
Good, thank you both! I'll revert the refactoring then.

**Comment by ManimMadhav** [comment]
I can reproduce this error in my code though, while using version ```7.7.6```.

**Comment by leyiang** [comment]
I have the same problem. (Ubuntu + chrome v123 + mouse)
I removed `package-lock.json`, `node_modules`, and set `"wavesurfer.js": "7.7.6"`.
Run `npm i`, and the problem's gone.

**Comment by katspaugh** [comment]
Thanks for confirming @leyiang, I’ll revert the commit that caused this.

**Comment by katspaugh** [comment]
Could you guys try on this branch? https://revert-draggable.wavesurfer-js.pages.dev/#regions.js

**Comment by leyiang** [comment]
> Could you guys try on this branch? https://revert-draggable.wavesurfer-js.pages.dev/#regions.js

I tried it, and there were no issues. (at least for me)

**Comment by katspaugh** [comment]
I've published v7.7.11 with a fix.

**Comment by ManimMadhav** [comment]
uhh when will this version be available on unpkg.com?

**Comment by katspaugh** [comment]
Unpkg seems to have been having issues lately, you migth want to switch to some other CDN (there are some suggestions in https://github.com/katspaugh/wavesurfer.js/issues/3650).

**Comment by ManimMadhav** [comment]
have they not yet been updated with v7.7.11?
all of them still show the latest version as v7.7.10 for me.

**Comment by katspaugh** [comment]
My bad, the package wasn’t published properly. I’ve just published 7.7.11 for real.

**Comment by ManimMadhav** [comment]
thank you so much for this speedy fix @katspaugh! 
it works great now :)
