### ISSUE TITLE
Overshoot of playback with MediaElement backend

### ISSUE THREAD

**Issue by Lingomat** [katspaugh/wavesurfer.js#709]
Calling a region's play() method often results in overshooting of playback by a significant amount. 

Similarly, calling pause() , the a current time set during the audioprocess callback also results in a time significantly beyond that expected.

This may be replicated in Aikuma-NG by going into settings and turning on preserve pitch which switches the backend of wavesurfer instances to MediaElement. Working in respeaking/translation will show the unexpected pause() overshoot, just playing back an annotation will show the region overshoot effect.

**Comment by katspaugh** [comment]
The [pause method](https://github.com/katspaugh/wavesurfer.js/blob/master/src/mediaelement.js#L117) just calls the Media Element's pause method. So it might simply be how browser works. Needs to be checked more closely anyway, so I'll mark this as a bug.

**Comment by Lingomat** [comment]
So this is interesting. The MediaElement backend code isn't very complicated for play with start and end. It looks like there's a simple hook into audioprocess. If playback time >= end time, pause, seek to end.

What's not clear to me is why when I do exactly the same thing manually, via Aikuma's respeak/translate feature, pausing is 99% of the time spot on. In this case the user is holding down a key, I'm hooking audioprocess and constantly updating the end point of a new region. They lift off the play/mark key and it fires pause. Why on earth would this be more accurate?!

**Comment by Lingomat** [comment]
The problem is the MediaElement timeupdate event. Frequency is dependent on 'load' whatever that means, and has a maximum interval of 250ms. It seems that the only way to do better would be to start a manual interval loop rather than relying on the timeupdate event. It seems like it wouldn't be hard to do outside of wavesurfer anyway, if it's useful (and it is totally useful for our use case).

**Comment by chrisparton1991** [comment]
@Lingomat Do you mean minimum interval duration is 250ms (i.e. no better than 4 times per second)?

I've come across a similar issue with jQuery UI, where the drag/drop events were too infrequent. In the drag/drop start event I call `setInterval()` with something like a 5ms interval, then call `clearInterval()` in the drag/drop stop event.

That approach worked much better for me, so I can see how it would make sense to apply this pattern here.

**Comment by Lingomat** [comment]
No, the interval can happen more quickly, Moz docs say:

> The event frequency is dependant on the system load, but will be thrown between about 4Hz and 66Hz (assuming the event handlers don't take longer than 250ms to run).

So it's not even that it can be unacceptably long, sometimes it's fine. I resolved this in Aikuma by using an interval. Seems to work nicely.

**Comment by chrisparton1991** [comment]
Ah okay, that makes sense. Thanks for the clarification.

I wonder if there's also potential to use an interval (or requestAnimationFrame) for the audio playback indicator line to make it smoother. Just a thought, and something for another issue.

**Comment by katspaugh** [comment]
`requestAnimationFrame` is already used for the progress animation. Maybe we should replace `timeupdate` with it indeed.

**Comment by Lingomat** [comment]
Speaking of MediaElement issues. I'm seeing an issue where 'ended' is firing well before the actual end of the audio for the mediaelement. Anyone seen that?

**Comment by Lingomat** [comment]
Hmm, the mediaelement backend might be a wash. It looks like the wavesurfer scale is not lined up with the length of source audio. This results in what looks like an early 'finish' being called in the middle of the display, but it's not early, it's right, it's just that the wavesurfer cursor is not moving fast enough. Weird huh?

**Comment by katspaugh** [comment]
Yes, I think Media Element is pretty inaccurate timing-wise. Switching to `requestAnimationFrame` should solve this pre-mature finish thing as well.

**Comment by Lingomat** [comment]
What about AudioContext.createMediaElementSource() ? 

To my mind, this would allow most of the Web Audio backend to work as is, particularly AudioContext.createScriptProcessor() with the attendant onaudioprocess. It would also have the advantage that Ogg Opus would be supported in Chrome (currently unsupported in Web Audio), and so would filters and so on. 



would be helpful in any way.

**Comment by katspaugh** [comment]
The point of the media element backend is to give an alternative to Web Audio.

Ogg Opus won't be supported anyway, because the problem is that Chrome cannot decode it. Unless you mean just playback without a waveform.

**Comment by DrLongGhost** [comment]
I am still seeing this issue present in Firefox 61 and Wavesurfer 2.0.5.

In Firefox only, if you play a recording from the start, the progress bar and waveform align properly with the audio being played back. However, if you stop the audio and then click on the waveform to move the playback location, when you click play again, the audio that is played back and the progress bar shown on the waveform are no longer in sync. Sometimes the issue won't manifest unless you zoom in and out or try the process several times.

The issue goes away if you do not use the MediaElement backend (or if you switch to a different browser).
