### ISSUE TITLE
MediaElement Cursor End Position

### ISSUE THREAD

**Issue by X-Raym** [katspaugh/wavesurfer.js#898]
Hi !

I noticed that with MediaElement,
the Cursor End Position is not always accurate : it is often a bit behind the end of the waveform.

![Screenshot](http://i.imgur.com/oJ9A1LO.gif)

I checked end cursor position:
```
wavesurfer.on('finish', function () {
  var position = wavesurfer.getCurrentTime();  
  console.log(position);
});
```

```
12.094486 // MediaElement
12.082729166666667 // WebAudio
```

Here is a [codepen demo](http://codepen.io/X-Raym/pen/NbedGY?editors=1111).

If this is not a bug but API limitations, maybe a function to set the cursor at end of canva if MediaElement backend could be added in wavesurfer-js ?

Thanks for your support !

**Comment by thijstriemstra** [comment]
@katspaugh i've been seeing this for years,never figured it out..

**Comment by X-Raym** [comment]
@thijstriemstra thanks for your confirmation, I thought I was the only one with the issue !

**Comment by thijstriemstra** [comment]
Im not only seeing this with media element back end.

**Comment by entonbiba** [comment]
@X-Raym @thijstriemstra 

When I check the buffer duration value for WebAudio and MediaElement in console they are the same. Might be a bug with `wavesurfer.getCurrentTime()` when using MediaElement as it doesn't update the return value in time.

I fixed it in the following way, but it's in the finish event.
````
  console.log(wavesurfer.backend.params.backend);
  if(wavesurfer.backend.params.backend=='MediaElement'){
    console.log(wavesurfer.backend.buffer.duration);
    var position = wavesurfer.backend.buffer.duration;
  } else{
    var position = wavesurfer.getCurrentTime();  
  }
  console.log(position);
````

![image](https://cloud.githubusercontent.com/assets/5193884/22393549/7b130096-e4d6-11e6-83ff-4ebb78b9e42f.png)

**Comment by X-Raym** [comment]
@thijstriemstra my solution was to ad this at finish event:
wavesurfer.on('finish', function () {
  var position = wavesurfer.getCurrentTime();  
  wavesurfer.seekTo(wavesurfer.getDuration()); // Go to end. There is a small jump.
});

But there is a small jump when we do that.

I wonder if a better solution could be found, and if this solution could be included right in wavesurfer.js, especially if all people using MediaElement backend get this issue.
MediaElement backend allow to seek the audio file even if it is not fully downloaded so it is quite useful.

**Comment by entonbiba** [comment]
@X-Raym It will check if MediaElement is used and use backend.buffer.duration property.
Needs some more testing before updating the mediaelement.js getDuration() function.

````
   getDuration: function () {
        var duration = this.media.duration; // this might have to be changed to this.buffer.duration instead to avoid jumping when using wavesurfer.seekTo(wavesurfer.getDuration())
        if (duration >= Infinity) { // streaming audio
            duration = this.media.seekable.end(0);
        }
        return duration;
    },
````

Here is the code for the manual fix:
http://codepen.io/entonbiba/pen/apVaJM

**Comment by X-Raym** [comment]
@entonbiba this can do the trick, I suppose !

**Comment by entonbiba** [comment]
#941 pull request

**Comment by thijstriemstra** [comment]
I've seen it with various wavefiles in this [videojs-wavesurfer](https://collab-project.github.io/videojs-wavesurfer/examples/index.html) demo but can't seem to reproduce it now.

**Comment by entonbiba** [comment]
This has been fixed in the latest version. #941

**Comment by X-Raym** [comment]
@entonbiba Oh sorry, I missed your answer !
I wanted to thank you for the fix :)

**Comment by entonbiba** [comment]
@X-Raym  :)

**Comment by X-Raym** [comment]
@entonbiba Hi !
I just tested this fix in version v2.0 beta 2, and despite the fact I get the same audio duration, the cursor positon is still not good.

![Screenshot](https://i.imgur.com/TSDUF4T.gif)

- Do you confirm ?
- Should I open another ticket ?

Thanks for your support!

**Comment by mspae** [comment]
Disclaimer: I have never looked into this issue.

It sounds as though it could be caused by floating points being inexact.

See
* https://stackoverflow.com/questions/1458633/how-to-deal-with-floating-point-number-precision-in-javascript
* https://en.wikipedia.org/wiki/Floating-point_arithmetic#Accuracy_problems

**Comment by X-Raym** [comment]
@mspae
hi ! thanks for taking a look !

IMHO it is not related to floating point precision, as the offset is pretty large compared to the rounding decimal value.

I think there is something else going on there... just like we had problem with media element length detection.

**Comment by X-Raym** [comment]
@mspae I just noticed that indeed, the MediaElement audio duration seems truncated , and we can see it right on my screenshot (I missed it somehow). The difference is so small (you have to go the the seventh decimal), I wonder if it has an effect. But there should be a way to make it works seamlessly.
Maybe should I open a new issue for this ?

**Comment by X-Raym** [comment]
@mspae Hi !

I just find the problem only occurs with wav file.

I open a new issue at it seems not directly related to this one:
https://github.com/katspaugh/wavesurfer.js/issues/1223
